/**
 * Auth Action Types
 */
export const AUTO_LOGIN_ERROR = 'AUTH/AUTO_LOGIN_ERROR';
export const SIGNUP_REQUEST = 'AUTH/SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'AUTH/SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'AUTH/SIGNUP_ERROR';
export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'AUTH/LOGIN_ERROR';
export const FETCH_PROFILE_REQUEST = 'AUTH/FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'AUTH/FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'AUTH/FETCH_PROFILE_ERROR';
export const LOGOUT = 'AUTH/LOGOUT';
/**
 * Articles Action Types
 */
export const ARTICLES_FETCH_REQUEST = 'ARTICLES/ARTICLES_FETCH_REQUEST';
export const ARTICLES_FETCH_SUCCESS = 'ARTICLES/ARTICLES_FETCH_SUCCESS';
export const ARTICLES_FETCH_ERROR = 'ARTICLES/ARTICLES_FETCH_ERROR';

export const ARTICLES_FETCH_SINGLE_REQUEST = 'ARTICLES/ARTICLES_FETCH_SINGLE_REQUEST';
export const ARTICLES_FETCH_SINGLE_SUCCESS = 'ARTICLES/ARTICLES_FETCH_SINGLE_SUCCESS';
export const ARTICLES_FETCH_SINGLE_ERROR = 'ARTICLES/ARTICLES_FETCH_SINGLE_ERROR';

export const ARTICLES_ADD_REQUEST = 'ARTICLES/ARTICLES_ADD_REQUEST';
export const ARTICLES_ADD_SUCCESS = 'ARTICLES/ARTICLES_ADD_SUCCESS';
export const ARTICLES_ADD_ERROR = 'ARTICLES/ARTICLES_ADD_ERROR';
export const ARTICLES_UPDATE_REQUEST = 'ARTICLES/ARTICLES_UPDATE_REQUEST';
export const ARTICLES_UPDATE_SUCCESS = 'ARTICLES/ARTICLES_UPDATE_SUCCESS';
export const ARTICLES_UPDATE_ERROR = 'ARTICLES/ARTICLES_UPDATE_ERROR';
export const ARTICLES_REMOVE_REQUEST = 'ARTICLES/ARTICLES_REMOVE_REQUEST';
export const ARTICLES_REMOVE_SUCCESS = 'ARTICLES/ARTICLES_REMOVE_SUCCESS';
export const ARTICLES_REMOVE_ERROR = 'ARTICLES/ARTICLES_REMOVE_ERROR';
/**
 * Categorys Action Types
 */
export const CATEGORYS_FETCH_REQUEST = 'CATEGORYS/CATEGORYS_FETCH_REQUEST';
export const CATEGORYS_FETCH_SUCCESS = 'CATEGORYS/CATEGORYS_FETCH_SUCCESS';
export const CATEGORYS_FETCH_ERROR = 'CATEGORYS/CATEGORYS_FETCH_ERROR';
export const CATEGORYS_FETCH_SINGLE_REQUEST = 'CATEGORYS/CATEGORYS_FETCH_SINGLE_REQUEST';
export const CATEGORYS_FETCH_SINGLE_SUCCESS = 'CATEGORYS/CATEGORYS_FETCH_SINGLE_SUCCESS';
export const CATEGORYS_FETCH_SINGLE_ERROR = 'CATEGORYS/CATEGORYS_FETCH_SINGLE_ERROR';
export const CATEGORYS_ADD_REQUEST = 'CATEGORYS/CATEGORYS_ADD_REQUEST';
export const CATEGORYS_ADD_SUCCESS = 'CATEGORYS/CATEGORYS_ADD_SUCCESS';
export const CATEGORYS_ADD_ERROR = 'CATEGORYS/CATEGORYS_ADD_ERROR';
export const CATEGORYS_UPDATE_REQUEST = 'CATEGORYS/CATEGORYS_UPDATE_REQUEST';
export const CATEGORYS_UPDATE_SUCCESS = 'CATEGORYS/CATEGORYS_UPDATE_SUCCESS';
export const CATEGORYS_UPDATE_ERROR = 'CATEGORYS/CATEGORYS_UPDATE_ERROR';
export const CATEGORYS_REMOVE_REQUEST = 'CATEGORYS/CATEGORYS_REMOVE_REQUEST';
export const CATEGORYS_REMOVE_SUCCESS = 'CATEGORYS/CATEGORYS_REMOVE_SUCCESS';
export const CATEGORYS_REMOVE_ERROR = 'CATEGORYS/CATEGORYS_REMOVE_ERROR';
/**
 * Users Action Types
 */
export const USERS_FETCH_REQUEST = 'USERS/USERS_FETCH_REQUEST';
export const USERS_FETCH_SUCCESS = 'USERS/USERS_FETCH_SUCCESS';
export const USERS_FETCH_ERROR = 'USERS/USERS_FETCH_ERROR';
export const USERS_ADD_REQUEST = 'USERS/USERS_ADD_REQUEST';
export const USERS_ADD_SUCCESS = 'USERS/USERS_ADD_SUCCESS';
export const USERS_ADD_ERROR = 'USERS/USERS_ADD_ERROR';
export const USERS_UPDATE_REQUEST = 'USERS/USERS_UPDATE_REQUEST';
export const USERS_UPDATE_SUCCESS = 'USERS/USERS_UPDATE_SUCCESS';
export const USERS_UPDATE_ERROR = 'USERS/USERS_UPDATE_ERROR';
export const USERS_REMOVE_REQUEST = 'USERS/USERS_REMOVE_REQUEST';
export const USERS_REMOVE_SUCCESS = 'USERS/USERS_REMOVE_SUCCESS';
export const USERS_REMOVE_ERROR = 'USERS/USERS_REMOVE_ERROR';